services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo_list
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8000:8080

  migration:
    build:
      context: migration/
    environment:
      - DB_HOST=mysql
