services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo_list
    ports:
      - 3306:3306
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8000:8080

  migration:
    build:
      context: migration/
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
